### ISSUE TITLE
Build actual function set

### ISSUE THREAD

**Issue by hannah-seltmann** [sejo95/EvolutionaryGaming#11]
We have to discuss, what we want in there.

**Comment by tupini07** [comment]
I finished adding the functions of table 1 (in atari paper), and just commited up to the `last` function of table 2 (commit 0310f8def46eb5724d8b97fcd981f2b5b602ddba). The next function should be `differences`, however I'm not sure what is meant by _... computational derivative of the 1D vector of x_ 

Do you know?

**Comment by tupini07** [comment]
I found another description for this function in the [MT-CGP: Mixed Type Cartesian Genetic Programming](http://blawg.juxi.net/papers/harding2012mtcgp.pdf) paper. 

It is defined as: 

> Returns a vector containing the differences between each pair in the input vector

**Comment by tupini07** [comment]
All functions in the Atari paper have been implemented except for the `DIFFERNCES` and `AVG_DIFFERENCES` ones.

**Comment by hannah-seltmann** [comment]
I think, _computational derivative_ means treating the vector as points sampled from a function and getting the derivative of that function at these points, like in [https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.gradient.html](url)

**Comment by hannah-seltmann** [comment]
That's a list of functions from CGP-IP that we could include:

- [ ] ADDC, SUBC, MULC, MINC, MAXC (add/substract/multiply/min/max _parameter_ with inp1)
- [ ] _Normalize -> scale pixels to between 0 and 255 (I think we already do that in the cell evaluation?)
- [x] SOBEL, SOBELX, SOBELY -> edge detection
- [x] threshold (for each pixel: output white if value > parameter, output black otherwise)
- [x] smoothMedian, smoothBilateral, smoothBlur, unsharpen
- [x] shift, shiftUp, shiftDown, shiftLeft, shiftRight
- [x] reScale -> downscale image by parameter and upscale again
- [x] gabor, resizeThenGabor
-  [x] localMin, localMax, localAvg, localNormalize -> apply these operations to neighborhoods
- [x] dilate, erode
- [x] laplace, canny
- [x] gaussianblur

**Comment by hannah-seltmann** [comment]
Although I think we maybe should only include openCV functions so that we can find out how much they add compared to just the atari paper.

**Comment by hannah-seltmann** [comment]
Added the SOBEL functions.

**Comment by hannah-seltmann** [comment]
Updated the list to have checkmarks, to keep track of what's done.

**Comment by tupini07** [comment]
perfect! Thanks :) I can also edit your comment so if I add any other functions I can mark them. But in the meantime I'll try to focus on #18. If I'm not mistaken we're only missing that, and finish creating the functionset, and then we're ready to run the evolution and make the report.

**Comment by tupini07** [comment]
>     * [ ]  _Normalize -> scale pixels to between 0 and 255 (I think we already do that in the cell evaluation?)

Yes, the Gym environment already gives the images with the pixel values in the range [0,255].

**Comment by tupini07** [comment]
>     * [ ]  _Normalize -> scale pixels to between 0 and 255 (I think we already do that in the cell evaluation?)

Yes, the Gym environment already gives the images with the pixel values in the range [0,255].

**Comment by hannah-seltmann** [comment]
I'm not sure what the difference is between _localMax_ and _dilate_ and between _localMin_ and _erode_.

**Comment by tupini07** [comment]
good point. Can consider them to be the same?

**Comment by hannah-seltmann** [comment]
> good point. Can consider them to be the same?

Sure, why not.

**Comment by hannah-seltmann** [comment]
And it seems like _localAvg_ is the same as _smoothBlur_.

**Comment by hannah-seltmann** [comment]
I think that's all of them.
