### ISSUE TITLE
is it good to have 2 versions of all functions with 1 arity in functionset?

### ISSUE THREAD

**Issue by tupini07** [sejo95/EvolutionaryGaming#16]
currently we have functions like `atan1` and `atan2`, which basically do the same but apply the `atan` to either `inp1` or `inp2`. 

I was thinking if this is actually necessary, since having duplicates of these functions increases the search space and doesn't provide much new functionality. On the other hand, it is nice to have _symmetric functions_. What do you guys think?

**Comment by tupini07** [comment]
I've added the functions for the _Statistical_ and _Comparison_ parts of table 1 (atari paper) in this commit 0310f8def46eb5724d8b97fcd981f2b5b602ddba . But I only added the _one sided_ version of the functions, until we decide this issue

**Comment by hannah-seltmann** [comment]
I think we can leave them in for now and remove them later if think that that improves the performance.
