### ISSUE TITLE
inspyred - Mutation

### ISSUE THREAD

**Issue by hannah-seltmann** [sejo95/EvolutionaryGaming#2]

**Comment by hannah-seltmann** [comment]
Is there anything still to do here?

**Comment by tupini07** [comment]
yes! This still needs to be implemented. 
Currently it only mutates all genes using a uniform distribution. But in the Atari paper the mutation of the output and inner nodes have specific probabilities and also the amount of recurrent loops generated by mutation needs to be controlled (currently we don't do this)
