### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by hannah-seltmann** [sejo95/EvolutionaryGaming#21]
- I think we should evaluate it on multiple different games.
- We should test each of these games with and without the opencv functions, to see if they help.
- We should settle on a set of random seeds, so that we can try each game with multiple different seeds and average the results. That's also good for reproducibility.

**Comment by tupini07** [comment]
1. I agree, luckily the game can easily be changed by setting the `ATARI_GAME` in the `constants` module to the appropriate value. Or we can also pass the name of the game as the second argument (see commit 3686443a0ac2dc02614fa304516fc6abe4b68ff5). Which games do you propose we evaluate? I was looking at the list of games and I think the following are interesting candidates:

- [Asteroids](https://gym.openai.com/envs/Asteroids-v0/)
- [Boxing](https://gym.openai.com/envs/Boxing-v0/)
- [Space Invader](https://gym.openai.com/envs/SpaceInvaders-v0)
- [Gravitar](https://gym.openai.com/envs/Gravitar-v0/)
- [Ms. Pacman](https://gym.openai.com/envs/MsPacman-v0/)

2. Sounds good.

3. I think we can run each game on 3 different seeds. What do you think about:

- 231
- 84
- 111

I've just made a commit that allows us to pass a seed as a command line argument when executing main:

`python main.py rng_seed`

By the way, I don't know if you noticed but when running the EA, all results get saved to a `results.csv` file, which includes the name of the game, the generation, and the fitness. These results are kept for each individual, and across multiple runs. We can then analyze the results based on this.

How many games do we want to try? I would say that 4 or 5 can be good enough. But it also depends on how long it takes to do the complete evaluation of each game.

**Comment by tupini07** [comment]
I made a bash script which runs the EA for every combination of game and seed. After running them the results of all runs should be saved in `results.csv`

**Comment by hannah-seltmann** [comment]
Do you know how long they take? We could split them if it is too long.

**Comment by tupini07** [comment]
I think that would be the best idea. I don't know exactly how long it will take, I image it also depends on each game. I'm just started running the Boxing game with seed 231, and will let you know as soon as it finishes (supposing there are no errors).

**Comment by hannah-seltmann** [comment]
Found another problem: we're giving the random seed to inspyred right now, but not to gym, so we can still have different results in different runs. I'm working on that now.

**Comment by hannah-seltmann** [comment]
> Found another problem: we're giving the random seed to inspyred right now, but not to gym, so we can still have different results in different runs. I'm working on that now.

Done

**Comment by tupini07** [comment]
Thanks! I refactored a bit your changes, since we don't need to have a separate `evaluate `or add the "seed" as an EA parameter, I'm just getting it as a normal `sys.argv` directly from the evolutionary problem module

**Comment by hannah-seltmann** [comment]
> Thanks! I refactored a bit your changes, since we don't need to have a separate `evaluate `or add the "seed" as an EA parameter, I'm just getting it as a normal `sys.argv` directly from the evolutionary problem module

That's neat. I didn't know this was possible. :)
