### ISSUE TITLE
Draw resulting function graph

### ISSUE THREAD

**Issue by tupini07** [sejo95/EvolutionaryGaming#7]
Just an idea, but might be nice to draw the best function graph found by the algorithm. We might use something like https://github.com/xflr6/graphviz to do it.

**Comment by hannah-seltmann** [comment]
Good idea. That would be useful for analysis.

**Comment by tupini07** [comment]
This has been implemented in `CGP_program.draw_function_graph` which draws an `svg` of a specific CGP program
