### ISSUE TITLE
Add node activation in CGP_program

### ISSUE THREAD

**Issue by hannah-seltmann** [sejo95/EvolutionaryGaming#8]
Not all nodes in a cartesian genetic program are connected to the outputs. Not computing the ones that aren't would save time. To do that, these nodes need to be marked as "inactive" and the evaluation function of the program needs to be adapted accordingly. See Wilson et.al., 2018 (the Atari paper) for algorithm.

**Comment by tupini07** [comment]
this has already been done right?

**Comment by hannah-seltmann** [comment]
Yeah, I was just keeping it open until the decision between recursive evaluation and this.

**Comment by tupini07** [comment]
😮  ok so we decided to stick with the iterative evalutaion right?
